### ISSUE TITLE
Unable to install helm chart on K8s 1.17.0

### ISSUE THREAD

**Issue by rayalaka** [skydive-project/skydive#2251] opened 2020-07-10 05:45 UTC
I tried installing [skydive helm chart](https://github.com/skydive-project/skydive-helm) on K8s 1.17.0 and I am facing errors.  Please find the below error message from logs

```
2020-07-10T05:37:44.600Z        WARN    k8s/probe.go:189 logOnError     5gobservability18.c4lab.local: github.com/skydive-project/skydive/topology/probes/k8s/cache.go:95: Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource
2020-07-10T05:37:44.600Z        WARN    k8s/probe.go:189 logOnError     5gobservability18.c4lab.local: github.com/skydive-project/skydive/topology/probes/k8s/cache.go:95: Failed to list *v1beta1.NetworkPolicy: the server could not find the requested resource
2020-07-10T05:37:44.600Z        WARN    k8s/probe.go:189 logOnError     5gobservability18.c4lab.local: github.com/skydive-project/skydive/topology/probes/k8s/cache.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
2020-07-10T05:37:45.601Z        WARN    k8s/probe.go:189 logOnError     5gobservability18.c4lab.local: github.com/skydive-project/skydive/topology/probes/k8s/cache.go:95: Failed to list *v1beta1.Deployment: the server could not find the requested resource
2020-07-10T05:37:45.601Z        WARN    k8s/probe.go:189 logOnError     5gobservability18.c4lab.local: github.com/skydive-project/skydive/topology/probes/k8s/cache.go:95: Failed to list *v1beta1.DaemonSet: the server could not find the requested resource
```

When I refer the implementation of skydive (https://github.com/skydive-project/skydive) I found that 'v1beta1` is used in multiple .go files. But, from the [kubernetes blog] (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) I see apis using v1beta is deprecated. 

Let me know if skydive is supported in K8s 1.17.0 version or am I missing something here.

**Comment by LoicLeGal** [comment] 2020-07-28 14:47
Seems to be duplicate of https://github.com/skydive-project/skydive/issues/2169

**Comment by lebauce** [comment] 2020-11-22 21:52
This should be fixed by https://github.com/skydive-project/skydive/pull/2267. Feel free to reopen it if necessary

**Closed** 2020-11-22 21:52 UTC
