### ISSUE TITLE
Interfaces without a host

### ISSUE THREAD

**Issue by carroarmato0** [skydive-project/skydive#313] opened 2017-07-19 15:37 UTC
Skydive 0.11.0

Sometimes in the UI, interfaces appear without being part of a host.

![screenshot from 2017-07-19 17-35-45](https://user-images.githubusercontent.com/1828645/28375825-d961ac38-6ca8-11e7-90f9-5907b7c9973e.png)

**Comment by safchain** [comment] 2017-07-19 16:00
It is a known issue of the 0.11, It should be fixed in master, so will be available in the next release (soon)

**Comment by carroarmato0** [comment] 2017-07-19 16:16
Great! :)

**Comment by safchain** [comment] 2017-07-21 16:04
I close it, feel free to re-open it if the issue is still present in the master branch

**Closed by safchain** 2017-07-21 16:04 UTC
