### ISSUE TITLE
In v0.12.0 inject packet check depends on netns is a error desgin

### ISSUE THREAD

**Issue by jonnary** [skydive-project/skydive#409] opened 2017-08-31 13:18 UTC
1.In v0.12.0 we change the inject packet and binding it to netns.This cause if the interface not in netns, it will can't be inject packet. 
For exampe, In openstack devstack enviroment, the vm's tap/qvo interfaces all not IPV4 ip in the interface, but we can see the Neutron ips in ui, 
2.This situation in v0.11.0 we can inject packet by skydive client

**Comment by jonnary** [comment] 2017-08-31 13:20
Have discussed with masco.

**Comment by ji-xuepeng** [comment] 2017-09-01 03:22
I have the same problem in v0.12.0
In my openstack devstack environment, the virtual ports of the VMs do not belong to any of the network namespaces, and the packet injection fails. 
In fact, nothing is shown when ip netns command is executed on the compute node.

**Comment by safchain** [comment] 2017-09-04 14:12
The issue is not related to netns. In fact tap doesn't have IPV4 but we report the IPV4 that the VM will use in the Neutron metadata section. 

Before this patch https://github.com/skydive-project/skydive/commit/f010aec562200aef936c1781a3904e64b8d20968
metadata of Neutron were replicated to the first level of metadata that's why the packet injector was able to find an IP. This was an error since the tap interface in reallity doesn't have an IP.

I think this should be fixed in the WebUI, adding something to help user to spoof the IP from the Neutron metadata

**Comment by ji-xuepeng** [comment] 2017-09-05 02:14
@safchain, I can not  inject packet successfully also when I use v0.11.0.  In my environment, there are two VMs created by openstack. OVS is uesed in the  environment. 
VM1:
IP:10.10.0.11
MAC:fa:16:3e:95:b0:b8
Interface:tapb3238674-88 bridge     qbrb3238674-88 virtio      fa:16:3e:95:b0:b8
VM2:
IP:10.10.0.6
IP:fa:16:3e:ae:10:c6
Interface:tapeec17485-2d bridge     qbreec17485-2d virtio      fa:16:3e:ae:10:c6

root@compute1:~# brctl show
bridge name     bridge id               STP enabled     interfaces
qbrb3238674-88          8000.36b39499a407       no              qvbb3238674-88
                                                        tapb3238674-88
qbreec17485-2d          8000.aa3935cbd0c4       no              qvbeec17485-2d
                                                        tapeec17485-2d
When I ping from vm1 to vm2, I can capture ICMP messages normally, as shown below:
root@compute1:~# tcpdump -vv -i tapb3238674-88
tcpdump: listening on tapb3238674-88, link-type EN10MB (Ethernet), capture size 262144 bytes
18:13:47.452289 IP (tos 0x0, ttl 64, id 11037, offset 0, flags [DF], proto ICMP (1), length 84)
    10.10.0.11 > 10.10.0.6: ICMP echo request, id 30465, seq 0, length 64
18:13:47.454433 IP (tos 0x0, ttl 64, id 17743, offset 0, flags [none], proto ICMP (1), length 84)
    10.10.0.6 > 10.10.0.11: ICMP echo reply, id 30465, seq 0, length 64
root@compute1:~# tcpdump -vv -i qvbb3238674-88
tcpdump: listening on qvbb3238674-88, link-type EN10MB (Ethernet), capture size 262144 bytes
18:13:47.452458 IP (tos 0x0, ttl 64, id 11037, offset 0, flags [DF], proto ICMP (1), length 84)
    10.10.0.11 > 10.10.0.6: ICMP echo request, id 30465, seq 0, length 64
18:13:47.454403 IP (tos 0x0, ttl 64, id 17743, offset 0, flags [none], proto ICMP (1), length 84)
    10.10.0.6 > 10.10.0.11: ICMP echo reply, id 30465, seq 0, length 64

But When I inject packets using skydive client, I can capture ICMP echo request packet, but no ICMP echo reply, as shown below.
skydive client inject-packet --src="G.V().Has('Name', 'tapb3238674-88')" --dst="G.V().Has('Name', 'tapeec17485-2d')" 
--type="icmp" --count=2 --srcIP="10.10.0.11/24" --dstIP="10.10.0.6/24" --srcMAC="fa:16:3e:95:b0:b8" 
--dstMAC="fa:16:3e:ae:10:c6"
root@compute1:~# tcpdump -vv -i tapb3238674-88
tcpdump: listening on qvbb3238674-88, link-type EN10MB (Ethernet), capture size 262144 bytes
18:14:05.814217 IP (tos 0x0, id 0, offset 0, flags [none], proto ICMP (1), length 28)
    10.10.0.11 > 10.10.0.6: ICMP echo request, id 0, seq 0, length 8
18:14:05.814235 IP (tos 0x0, id 0, offset 0, flags [none], proto ICMP (1), length 28)
    10.10.0.11 > 10.10.0.6: ICMP echo request, id 0, seq 0, length 8
root@compute1:~# tcpdump -vv -i qvbb3238674-88
tcpdump: listening on qvbb3238674-88, link-type EN10MB (Ethernet), capture size 262144 bytes

In fact, I capture nothing on interface qvbb3238674-88 using tcpdump. 
So I suspect that the ICMP message has not been sent out. I don't know what is the reason. Can you give me some help?
by the way,  the test case in packet_injector_test.go is ok in my environment.

**Comment by ji-xuepeng** [comment] 2017-09-06 00:45
I have known the reason. The ICMP message injected is in the wrong direction.

**Closed** 2017-09-11 13:45 UTC
Labels: bug, working-on-it
