### ISSUE TITLE
libvirtgo: ctx.Logger is not initialized causing panic

### ISSUE THREAD

**Issue by tu-pm** [skydive-project/skydive#2147] opened 2020-02-06 11:07 UTC
[Here](https://github.com/skydive-project/skydive/blob/225c23e94d83367fc202ba21590da1dd1e941261/topology/probes/libvirt/libvirtgo.go#L72) the `m.ctx.Logger` is not yet initialized (because the [initializer]() actually never does), causing panic when writing error log to the logger.

Error log:

```
panic: LibvirtgoMonitor &{Connect:0xc0007f6000 ctx:{Logger:<nil> Config:<nil> Graph:<nil> RootNode:<nil>} cidLifecycle:0 cidDevAdded:1} encounter problem during d[7/9516$
ation: virError(Code=1, Domain=7, Message='internal error: client socket is closed')

goroutine 178 [running]:
github.com/skydive-project/skydive/topology/probes/libvirt.(*LibvirtgoMonitor).Stop(0xc0001dc0f0)
        /home/tupham/go/src/github.com/skydive-project/skydive/topology/probes/libvirt/libvirtgo.go:76 +0x294
github.com/skydive-project/skydive/topology/probes/libvirt.newMonitor.func4(0xc0008bd8f8, 0x1)
        /home/tupham/go/src/github.com/skydive-project/skydive/topology/probes/libvirt/libvirtgo.go:155 +0x70
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go.closeCallback(0x7f0bd4001380, 0x1, 0x66)
        /home/tupham/go/src/github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go/connect.go:492 +0x8a
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go._cgoexpwrap_8c8618fe7399_closeCallback(0x7f0bd4001380, 0x1, 0x66)
        _cgo_gotypes.go:8579 +0x3f
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go._Cfunc_virDomainGetXMLDescWrapper(0x7f0b6c0088c0, 0xc000000000, 0xc0013620a0, 0x0)
        _cgo_gotypes.go:4056 +0x4e
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go.(*Domain).GetXMLDesc.func1(0xc000f039f0, 0x0, 0xc0013620a0, 0x0)
        /home/tupham/go/src/github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go/domain.go:1114 +0xe3
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go.(*Domain).GetXMLDesc(0xc000f039f0, 0x0, 0xc0003666f0, 0xc000366720, 0x0, 0xc00042bf01)
        /home/tupham/go/src/github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go/domain.go:1114 +0x5e
github.com/skydive-project/skydive/topology/probes/libvirt.libvirtgoDomain.GetXML(0x7f0b6c0088c0, 0xc000f03a48, 0xe04ada, 0xc00059ad20, 0x0, 0xc000f03a01)
        /home/tupham/go/src/github.com/skydive-project/skydive/topology/probes/libvirt/libvirtgo.go:41 +0x38
github.com/skydive-project/skydive/topology/probes/libvirt.(*Probe).getNovaMetadata(0xc0003cb260, 0x3b3a880, 0x7f0b6c0088c0, 0xc00077ce10, 0xc000ea1968, 0x0)
        /home/tupham/go/src/github.com/skydive-project/skydive/topology/probes/libvirt/libvirt.go:221 +0x35
github.com/skydive-project/skydive/topology/probes/libvirt.(*Probe).createOrUpdateDomain(0xc0003cb260, 0x3b3a880, 0x7f0b6c0088c0, 0x0)
        /home/tupham/go/src/github.com/skydive-project/skydive/topology/probes/libvirt/libvirt.go:414 +0x47a
github.com/skydive-project/skydive/topology/probes/libvirt.newMonitor.func2(0xc000920370, 0xc000920368, 0xc000957970)
        /home/tupham/go/src/github.com/skydive-project/skydive/topology/probes/libvirt/libvirtgo.go:127 +0x60
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go.domainEventLifecycleCallback(0x7f0bd4001380, 0x7f0b6c0088c0, 0x4, 0x0, 0x64)
        /home/tupham/go/src/github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go/domain_events.go:238 +0xf2
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go._cgoexpwrap_8c8618fe7399_domainEventLifecycleCallback(0x7f0bd4001380, 0x7f0b6c0088c0, 0x4, 0x0, 0$
64)
        _cgo_gotypes.go:8592 +0x53
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go._Cfunc_virEventRunDefaultImplWrapper(0xc000be2550, 0xc000000000)
        _cgo_gotypes.go:5964 +0x49
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go.EventRunDefaultImpl.func1(0xc000be2550, 0xc000be2550)
        /home/tupham/go/src/github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go/events.go:57 +0x9d
github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go.EventRunDefaultImpl(0xc000070d80, 0x0)
        /home/tupham/go/src/github.com/skydive-project/skydive/vendor/github.com/libvirt/libvirt-go/events.go:57 +0x44
github.com/skydive-project/skydive/topology/probes/libvirt.newMonitor.func1(0x3b38580, 0xc000070d80, 0xc0003cb260)
        /home/tupham/go/src/github.com/skydive-project/skydive/topology/probes/libvirt/libvirtgo.go:102 +0x46
created by github.com/skydive-project/skydive/topology/probes/libvirt.newMonitor
        /home/tupham/go/src/github.com/skydive-project/skydive/topology/probes/libvirt/libvirtgo.go:100 +0x11f
```

**Comment by lebauce** [comment] 2020-02-06 11:13
@tu-pm Thanks for reporting this. As a workaround before the issue is fixed, you can compile with WITH_LIBVIRT_GO=true to use the pure Go version of the libvirt probe

**Comment by lebauce** [comment] 2020-02-06 11:19
Could you please give the https://github.com/skydive-project/skydive/pull/2148 PR a try ? Thanks !

**Comment by safchain** [comment] 2020-02-17 23:55
Closing as the PR has been merged, feel free to re-open if needed

**Closed by safchain** 2020-02-17 23:55 UTC
