### ISSUE TITLE
Flows() step does not work with ShortestPathTo() step

### ISSUE THREAD

**Issue by eonpatapon** [skydive-project/skydive#202] opened 2017-01-27 14:06 UTC
For ex: `G.V().Has('TID', '47f0188c-47d8-50e4-775c-93fa4b9d664c').ShortestPathTo(Metadata('TID', '57daef32-0ae1-528d-717e-09828369aaeb'), Metadata('RelationType', 'layer2')).Flows()`

Will return: `400 Bad Request: Error while executing the query`

**Comment by safchain** [comment] 2017-01-28 10:03
Confirmed. This is because ShortestPathTo returns an array of array of nodes and not an array of nodes as we can have multiple shortest path is case of not using TID and having more than 1 node as source. Anyway the Flows step needs to be fixed.

**Comment by masco-enovance** [comment] 2017-03-31 17:09
https://softwarefactory-project.io/r/#/c/7322/

**Comment by masco-enovance** [comment] 2017-04-20 17:36
fix was merged.

**Closed by masco-enovance** 2017-04-20 17:36 UTC
Labels: bug
