### ISSUE TITLE
Elasticsearch  MapperParsingException nested: IllegalArgumentException on epoch_second

### ISSUE THREAD

**Issue by nplanel** [skydive-project/skydive#185] opened 2016-12-09 02:10 UTC
On Fedora 24  elasticsearch-1.7.1-3.fc24.noarch

Start allinone, tunnel.sh, ping ...

2016-12-09T13:08:23.425+11:00 X1:analyzer elasticsearch.go:134 elasticsearch (*ElasticSearchStorage).StoreFlows > ERRO 049 Error while indexing: 2016-12-09 13:08:23.425123413 +1100 AEDT: Error [MapperParsingException[failed to parse]; nested: IllegalArgumentException[Invalid format: [epoch_second]: Illegal pattern component: p]; nested: IllegalArgumentException[Illegal pattern component: p]; ] Status [400] [400]

**Comment by safchain** [comment] 2016-12-09 07:51
As we specify than ES > 2.0 is a requierement in the documentation not sure it's a bug

http://skydive-project.github.io/skydive/getting-started/install/

**Comment by safchain** [comment] 2017-01-28 10:04
Closing this one as it's not a bug but a deployment issue

**Closed by safchain** 2017-01-28 10:04 UTC
Labels: bug

**Comment by nplanel** [comment] 2017-01-28 15:04
Yep forgot to closed it
