### ISSUE TITLE
Evaluate germlin capture when start the Agent

### ISSUE THREAD

**Issue by nplanel** [skydive-project/skydive#186] opened 2016-12-09 03:20 UTC
If you start a new Agent (or restart for example), the gremlin capture like g.V().Has("Type", "veth") will not be evaluated during startup of the Agent.
So no capture probe will be launched.

**Comment by safchain** [comment] 2016-12-09 07:55
Yes, and the agent seems to be blocked somewhere

**Comment by lebauce** [comment] 2016-12-30 10:30
I can not reproduce the bug. Could you try again on master ?

**Comment by kdorfman** [comment] 2017-01-12 13:04
I've reproduced this today.

**Comment by kdorfman** [comment] 2017-01-23 08:39
probably resolved by https://softwarefactory-project.io/r/#/c/6094/

**Closed** 2017-01-23 15:33 UTC
