### ISSUE TITLE
Failed to delete the Captures without any flow packets in memory

### ISSUE THREAD

**Issue by iamingithub** [skydive-project/skydive#1323] opened 2018-09-18 11:05 UTC
Issues:
We create a Capture on a node, but the node can not capture packets, for example, in flow/probes/gopacket.go, it will be endless loop in the method run()--p.feedFlowTable(), so that it will not execute e.OnStopped() to clean the capture of the node in memory. Although the capture has been deleted in the etcd, but the Capture goroutine will be running, and the Metadata of the node have the Capture information forever until we restart Skydive.

Solution:
We should execute p.handle.close() in method stop(),  instead of executing it behind p.feedFlowTable() in run(), there are some things to do, for example, in flow/probes/afpacket.go, we should resolve synchronization issue when we execute p.handle.close() first.
I have resolved it and test for a long time in our team.
Please check, i can commit my codes if it does be a bug, thanks

**Comment by safchain** [comment] 2018-09-18 13:03
FeedFlowTable relies on the AfPacket Timeout to check the capture state and exit. I'm going to reproduce the issue in order to understand why the timeout thing is not working. Thanks for reporting this issue.

**Comment by iamingithub** [comment] 2018-09-19 01:00
> FeedFlowTable relies on the AfPacket Timeout to check the capture state and exit. I'm going to reproduce the issue in order to understand why the timeout thing is not working. Thanks for reporting this issue.

Ok. I found the main issues is that it will be endless loop in the method run()--p.feedFlowTable()--p.packetSource.NextPacket() when we don't received data even if we execute stop(). No matter whether pcap or afpacket, p.packetSource.NextPacket() will be endless loop until we received data, if timeout or  we received empty block it will retry until we received data.
I hope it will be helpful, thanks.

**Comment by safchain** [comment] 2018-09-19 07:27
There is no endless loop ? the loop is controlled by an atomic state
https://github.com/skydive-project/skydive/blob/master/flow/probes/gopacket.go#L120

This state is modified by the stop() function
https://github.com/skydive-project/skydive/blob/master/flow/probes/gopacket.go#L268

I do not see any other loop, can you point me where in the code is the infinite loop ?

I did try to reproduce without success but with afpacket there is a timeout issue that I just fixed and an issue with the probe unregister mechanism due to gremlin

**Comment by safchain** [comment] 2018-09-19 08:31
in case of timeout it should be this line 

https://github.com/skydive-project/skydive/blob/4118a27ddc0f58dd325391627e20b4bd6405f223/flow/probes/afpacket/afpacket.go#L267 

which will stop the retry as pollForFirstPacket will return an error
https://github.com/google/gopacket/blob/master/afpacket/afpacket.go#L465


I did exactly this without being able to reproduce :(

**Comment by safchain** [comment] 2018-09-19 09:16
or it means that you always receive an empty block. what kernel/os ? what kind of interface ? do you have this on every interface ?

**Comment by iamingithub** [comment] 2018-09-19 09:47
It maybe relate to environment.
os: CentOS
env: ovs , ovs2.8+dpdk
interface: for example, Physical Network Interface，which has not ip

**Comment by safchain** [comment] 2018-10-03 15:20
We merged some patches around afpacket issue can you have another try please ?

**Comment by lebauce** [comment] 2018-10-15 12:50
@iamingithub PTAL

**Comment by safchain** [comment] 2018-11-05 10:12
Closing it for now, feel free to re-open if needed

**Closed by safchain** 2018-11-05 10:12 UTC
