### ISSUE TITLE
skydive crashes when have illegal line on analyzer.fabric in skydive.yaml

### ISSUE THREAD

**Issue by KalmanMeth** [skydive-project/skydive#1613] opened 2019-01-21 15:26 UTC
I added 
```
TOR1_PORT2 --> *[Type=host]/eno16
```
in skydive.yaml resulting in skydive analyzer crashing.

```
2019-01-21T15:23:45.643Z        ERROR   fabric/fabric.go:159 (*Probe).Start     pok1-qz1-sr1-rk004-s19: Fabric link definition should have two endpoints: TOR1_PORT2
2019-01-21T15:23:45.644Z        INFO    hub/replication_endpoint.go:112 (*TopologyReplicatorPeer).connect       pok1-qz1-sr1-rk004-s19: Connecting to peer: ws://0.0.0.0:8082/ws/replication
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/skydive-project/skydive/topology/probes/fabric.nodeDefToMetadata(0x0, 0x0, 0x21c1ea0, 0xc421721901, 0xc42046eea0, 0xc4217219b8, 0x40e467)
        /home/vagrant/go/src/github.com/skydive-project/skydive/topology/probes/fabric/fabric.go:108 +0x2c9
github.com/skydive-project/skydive/topology/probes/fabric.(*Probe).getOrCreateFabricNodeFromDef(0xc4205734b0, 0x0, 0x0, 0x4, 0xc42046ef28, 0x2)
        /home/vagrant/go/src/github.com/skydive-project/skydive/topology/probes/fabric/fabric.go:122 +0x4d
github.com/skydive-project/skydive/topology/probes/fabric.(*Probe).Start(0xc4205734b0)
        /home/vagrant/go/src/github.com/skydive-project/skydive/topology/probes/fabric/fabric.go:212 +0x7df
github.com/skydive-project/skydive/probe.(*Bundle).Start(0xc420177f60)
        /home/vagrant/go/src/github.com/skydive-project/skydive/probe/bundle.go:45 +0xc6
github.com/skydive-project/skydive/analyzer.(*Server).Start(0xc4223f3e80, 0x0, 0x0)
        /home/vagrant/go/src/github.com/skydive-project/skydive/analyzer/server.go:130 +0x8a
github.com/skydive-project/skydive/cmd/analyzer.glob..func1(0x3836700, 0xc420176da0, 0x0, 0x2)
        /home/vagrant/go/src/github.com/skydive-project/skydive/cmd/analyzer/analyzer.go:55 +0x117
github.com/skydive-project/skydive/vendor/github.com/spf13/cobra.(*Command).execute(0x3836700, 0xc420176c00, 0x2, 0x2, 0x3836700, 0xc420176c00)
        /home/vagrant/go/src/github.com/skydive-project/skydive/vendor/github.com/spf13/cobra/command.go:603 +0x234
github.com/skydive-project/skydive/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x383be20, 0x3836700, 0x38362c0, 0xc420753f50)
        /home/vagrant/go/src/github.com/skydive-project/skydive/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
github.com/skydive-project/skydive/vendor/github.com/spf13/cobra.(*Command).Execute(0x383be20, 0xc420753f70, 0x1c3aa64)
        /home/vagrant/go/src/github.com/skydive-project/skydive/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /home/vagrant/go/src/github.com/skydive-project/skydive/skydive.go:32 +0x2d
```

**Comment by lebauce** [comment] 2019-01-21 16:18
Could you please post the full `fabric` section ? I can't reproduce the bug. Thanks !

**Comment by KalmanMeth** [comment] 2019-01-22 08:01
Full fabric section:

    fabric:
      # - TOR[Name=tor] -> TOR_PORT1[Name=port1]
      # - TOR1[Name=tor1] -> TOR1_PORT1[Name=port1]
      # - TOR1[Name=tor1] -> [color=red] TOR1_PORT2[Name=port2, MTU=1500]
      # - TOR_PORT1 --> TOR1_PORT1
      # - TOR1_PORT2 --> *[Type=host]/eth0
      TOR1_PORT2 --> *[Type=host]/eno16

**Comment by lebauce** [comment] 2019-01-22 08:54
Addressed by https://github.com/skydive-project/skydive/pull/1615

**Comment by safchain** [comment] 2019-01-23 17:16
@KalmanMeth can we close it now ?

**Closed** 2019-01-24 08:00 UTC
